default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["db_host"] %>
  username: <%= ENV["db_username"] %>
  password: <%= ENV["db_password"] %>


development:
  <<: *default
  database: OnlineExam_development

test:
  <<: *default
  database: OnlineExam_test

production:
  <<: *default
  database: OnlineExam_production
  username: OnlineExam
  password: <%= ENV["ONLINEEXAM_DATABASE_PASSWORD"] %>
